---

- block:
    - name: End play if not running on HPE server
      debug:
        msg: "System Vendor: {{ ansible_system_vendor }}"
    - meta: end_play
  when: ansible_system_vendor != 'HP'

- name: Detect server product name
  debug:
    msg: "Product Name: {{ ansible_product_name }}"
