---

  # HPE Software Repos
  # HPE has not released repo for bionic yet, so we use xenial until the newer version is released.
- name: Add HPE Apt Software repos
  apt_repository:
    filename: "mcp"
    repo: "deb http://downloads.linux.hpe.com/SDR/repo/mcp {{ hpe_dist }}/{{ hpe_project_ver }} non-free"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add HPE Yum Software Repository
  yum_repository:
    name: "mcp"
    state: present
    description: "Management Component Pack"
    baseurl: "http://downloads.linux.hpe.com/repo/mcp/{{ hpe_dist }}/{{ hpe_dist_ver }}/{{ hpe_arch }}/{{ hpe_project_ver }}"
    enabled: yes
    gpgcheck: no
    gpgkey: "https://downloads.linux.hpe.com/SDR/hpPublicKey1024.pub
             https://downloads.linux.hpe.com/SDR/hpPublicKey2048.pub
             https://downloads.linux.hpe.com/SDR/hpPublicKey2048_key1.pub
             https://downloads.linux.hpe.com/SDR/hpePublicKey2048_key1.pub"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Add HPE Apt signing keys
  apt_key: url="{{ item }}" state=present
  with_items:
    - "https://downloads.linux.hpe.com/SDR/hpPublicKey1024.pub"
    - "https://downloads.linux.hpe.com/SDR/hpPublicKey2048.pub"
    - "https://downloads.linux.hpe.com/SDR/hpPublicKey2048_key1.pub"
    - "https://downloads.linux.hpe.com/SDR/hpePublicKey2048_key1.pub"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install HPE Softwares
  package:
    name: "{{ hpe_pkgs }}"
    state: present
    update_cache: "{{ omit if ansible_pkg_mgr == 'yum' else 'yes' }}"
