---

hpe_dist: "{{ ansible_distribution }}"
hpe_dist_ver: "{{ ansible_distribution_major_version }}"
hpe_arch: "{{ ansible_architecture }}"

hpe_pkgs:
  - hp-health
  - hponcfg
  - hp-ams
  - hp-snmp-agents
  - hpsmh
  - hp-smh-templates
  - ssacli
  - ssaducli
  - ssa
  - lldpd
